version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - 80
          - 443
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver2022
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_PID=Express
          - MSSQL_SA_PASSWORD=12345Abc%
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.0
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
          - "9092:9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
volumes:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: bridge
  